#!/usr/bin/env bash
# Write .env for live Muse Glimmer chat presets.
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

PRESET="${1:-}"
if [[ -z "$PRESET" ]]; then
  cat <<'EOF'
Usage: ./scripts/configure-live.sh <preset>

Presets:
  llamacpp       Local llama.cpp OpenAI server (default port 8080)
  hf-endpoint    Hugging Face Inference Endpoint (needs HF_ENDPOINT_URL + HF_TOKEN)
  openrouter     OpenRouter OpenAI-compatible API
  custom         Prompt for base URL / key / model

Env overrides (any preset):
  OPENAI_BASE_URL  OPENAI_API_KEY  OPENAI_MODEL  HF_TOKEN  HF_ENDPOINT_URL
  LLAMA_PORT       OPENROUTER_API_KEY
EOF
  exit 1
fi

PORT_LAB="${PORT:-7870}"
HOST_LAB="${HOST:-127.0.0.1}"

write_env() {
  local base="$1" key="$2" model="$3" provider="$4"
  # Normalize: ensure /v1, no trailing slash beyond that
  base="${base%/}"
  if [[ "$base" != */v1 ]]; then
    base="${base}/v1"
  fi
  cat > .env <<EOF
# Generated by scripts/configure-live.sh (${provider}) — do not commit
HOST=${HOST_LAB}
PORT=${PORT_LAB}
LIVE_PROVIDER=${provider}
OPENAI_BASE_URL=${base}
OPENAI_API_KEY=${key}
OPENAI_MODEL=${model}
EOF
  echo "Wrote $ROOT/.env"
  echo "  LIVE_PROVIDER=${provider}"
  echo "  OPENAI_BASE_URL=${base}"
  echo "  OPENAI_MODEL=${model:-"(auto from /v1/models)"}"
  echo "  OPENAI_API_KEY=$([ -n "$key" ] && echo '(set)' || echo '(empty)')"
  echo
  echo "Next: ./scripts/probe-live.sh   # or start the lab: ./run.sh"
}

case "$PRESET" in
  llamacpp|llama|llama.cpp)
    LP="${LLAMA_PORT:-8080}"
    BASE="${OPENAI_BASE_URL:-http://127.0.0.1:${LP}}"
    KEY="${OPENAI_API_KEY:-}"
    MODEL="${OPENAI_MODEL:-}"
    write_env "$BASE" "$KEY" "$MODEL" "llamacpp"
    echo "Tip: start the server with ./scripts/serve-llamacpp.sh"
    ;;
  hf-endpoint|hf|huggingface)
    URL="${HF_ENDPOINT_URL:-${OPENAI_BASE_URL:-}}"
    if [[ -z "$URL" ]]; then
      echo "Set HF_ENDPOINT_URL (e.g. https://xxxx.us-east-1.aws.endpoints.huggingface.cloud)" >&2
      exit 1
    fi
    KEY="${OPENAI_API_KEY:-${HF_TOKEN:-}}"
    if [[ -z "$KEY" ]]; then
      echo "Set HF_TOKEN or OPENAI_API_KEY" >&2
      exit 1
    fi
    MODEL="${OPENAI_MODEL:-meta-models/Muse-Glimmer-30B}"
    write_env "$URL" "$KEY" "$MODEL" "hf-endpoint"
    ;;
  openrouter)
    KEY="${OPENAI_API_KEY:-${OPENROUTER_API_KEY:-}}"
    if [[ -z "$KEY" ]]; then
      echo "Set OPENROUTER_API_KEY or OPENAI_API_KEY" >&2
      exit 1
    fi
    BASE="${OPENAI_BASE_URL:-https://openrouter.ai/api/v1}"
    MODEL="${OPENAI_MODEL:-meta-models/Muse-Glimmer-30B}"
    write_env "$BASE" "$KEY" "$MODEL" "openrouter"
    echo "Confirm OPENAI_MODEL matches OpenRouter's catalog id for Muse Glimmer."
    ;;
  custom)
    read -r -p "OPENAI_BASE_URL: " BASE
    read -r -p "OPENAI_API_KEY (blank ok): " KEY
    read -r -p "OPENAI_MODEL (blank = auto): " MODEL
    write_env "$BASE" "$KEY" "$MODEL" "custom"
    ;;
  *)
    echo "Unknown preset: $PRESET" >&2
    exit 1
    ;;
esac
